sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: 数据分析
name: 大数据分析开发成长记录
description: 一个数据分析开发同学的博客

github: https://github.com/maolilai/maolilai.github.io
rss: true

comment_gitment_repo: maolilai.github.io
comment_gitment_clientId: a5bff4405a39356a082f
comment_gitment_clientSecret: aec3e919f4783e4d09dce33970debc8bb039f902

gitment_client_id: a5bff4405a39356a082f
site.gitment_secret: aec3e919f4783e4d09dce33970debc8bb039f902

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock

theme: jekyll-theme-minimal